### ISSUE TITLE
Buienalarm wekt niet goed

### ISSUE THREAD

**Issue by Dgh1974** [magtimmermans/com.cyclone-software.buienalarm#18]
Hi

ik heb een advance flow met 3 meldingen over regen ( ALS : 10 min - 5 min en als het regent)

de app geeft aan dat er regen gaat vallen binnen 10 mins  ( 0.6 )
Maar dat triggered niets in de advanced flow ) ?

Ik heb screenshots van het moment en deel van de flow

![IMG_8237](https://github.com/user-attachments/assets/3102a0a1-99d5-46fe-9817-c6f267f68686)
![IMG_8238](https://github.com/user-attachments/assets/1dcb85bf-ba77-4b75-8d6b-57ca4620577a)

**Comment by wannes62** [comment]
Ik loop tegen hetzelfde probleem aan. 
Als het over 5 minuten gaat regenen dan zou mijn zonnescherm omhoog moeten gaan, maar dat doet hij dus niet.
![Schermafbeelding 2024-09-11 144412](https://github.com/user-attachments/assets/bc2e4af9-f099-4147-a046-24a19407338a)

**Comment by EdwinO66** [comment]
Iemand enig idee hoe ik de coordinaten / locatie kan aanpassen?
Bij configuratie zie ik de coordinaten staan maar kan ik hem niet aanpassen.

**Comment by magtimmermans** [comment]
Dat zijn de coordinaten die je in homey instelt. Dus de positie van je Homey.

**Comment by EdwinO66** [comment]
> Dat zijn de coordinaten die je in homey instelt. Dus de positie van je Homey.

Thanks!, na een herstart van Homey en de app pakt hij nu de goede coördinaten.

**Comment by Dgh1974** [comment]
Hi marcel ... enig idee hoe het kan dat het niet werkt ?

**Comment by magtimmermans** [comment]
Sorry, voor late antwoord. Ik was met vakantie. Ik heb eigenlijk de log van de app nodig. Dus op het moment dat hij het weer niet doet. Stuur dan even de log op. Want dit kan aan verschillende dingen liggen. Soms geeft weer station geen data. Internet connectie. etc.

**Comment by Dgh1974** [comment]
Doe ik .. zal niet meevallen om het exacte moment te vinden ... waar moet ik dat posten ? Gewoon hier als attachment?

**Comment by magtimmermans** [comment]
Je kan bij de App settings diagnostic report sturen. Dat is okay.

**Comment by Dgh1974** [comment]
Hi marcel

3 voorbeelden met screenshots en daaronder 3 rapportjes 

1 met 1 trigger die zou koeten werken ( 10 mins )

1 met 2 triggers die zou moeten werken ( 10 - 5 mins )

1 die werkt op 10 mins ... terwijl er dan 0 regen is 


![image](https://github.com/user-attachments/assets/e48cf32a-66f7-4f16-89af-0553e6bc8b67)

![image](https://github.com/user-attachments/assets/e914bea0-73c2-4dc2-b64f-e45401140457)


![image](https://github.com/user-attachments/assets/da38713b-75b0-4aa0-8cb4-847cf0283e99)

![image](https://github.com/user-attachments/assets/eea6d355-9b3b-409d-a659-2e54960fb682)


![image](https://github.com/user-attachments/assets/422a8c5c-8158-46de-979b-266ceace5195)

![image](https://github.com/user-attachments/assets/e66cdc78-5462-4b4c-bcef-332f846fd222)


8f1c2f9d-b9e4-4fb6-9f6f-15df2f4143ec

1c354bee-3bb6-47c8-853d-2c097c6175b9

a4323e95-e82d-4f17-be71-5c593d22597b

**Comment by magtimmermans** [comment]
Ik heb even snel gekeken maar ik duik er nog even verder in. In de logfiles die je gestuurd heb staat regelmatig dat hij de data niet kan laden van BuienAlarm. Geen idee waarom (internet probleem) of wat anders. Ik zal er in de komende dagen als ik wat meer tijd heb verder induiken.

**Comment by Dgh1974** [comment]
Top 👍

Internetproblemen waren niet aanwezig. Voorheen werkte het trouwens spontaan na een restart van de app

Dit lukte vandaag niet trouwens

**Comment by magtimmermans** [comment]
Ik snap het even niet. De error zegt dat de verbinding niet tot stand kan worden gebracht. (Internet issue of iets anders). Het gaat 2 keer goed en daarna niet meer. (Error at BuienAlarmGrabber.getForecasts (/app/BuienAlarmGrabber.js:23:22) at process.processTicksAndRejections).
Als ik hier jouw coordinaten invoer en heb het nu een dag laten draaien krijg ik netjes een notificatie 10 min voor dat de regen valt. In de logfiles van mijnzelf zie ik ook geen fout melding. En in alle die de logfiles die jij hebt gestuurd heb ik elke derde poging een foutmelding. Of dat toeval is weet ik niet.

**Comment by Dgh1974** [comment]
Hmmm

Ten eerste : bedankt voor uw tijd en gepuzzel !

Ja ik zie in de app ook netjes de tijden … maar op het moment dat de trigger gegeven moet worden … dan ziet de flow de juiste app settings niet ofzo.

Ik werk thuis en heb helemaal geen problemen met internet voor zover ik kan merken.

Daarbij … de gegevens zijn in de app settings correct ( dus geladen lijkt me ) … ECHTER de flowKAART maakt een andere keuze

Dus als VOORBEELD

1) buienalarm app op mijn telefoon geeft melding ( ik zie over 10 mins )

2) … ik check uw homey app instellingen en de tijd geeft daadwerkelijk neerslag over 10 mins

3) de flow zoals in screenshots geeft aan dat dat er over 10 mins GEEN regen valt ( immers de keuze tussen true/ false van het kaartje geeft aan dat het droog blijft )

In mijn laatste screenshot van gisteren was het zelfs andersom … buienradar / homey app settings geven dan droog over 10 mins ..
De kaart in de flow geeft aan dat het gaat regenen

Ik hoop dat dat iets duidelijker is

Zal een hele puzzel zijn denk ik :-(

Kan het dan nog met de intensiteit van de regen te maken hebben
Deze is niet selecteerbaar  in “en” flows … ik  weet niet wat de kaart bijvoorbeeld alleen in “matig” denkt en de andere opties dus niet ziet.

Of ergens misschien een error in de tijd ofzo ?
Dus app settings geven 10 mins … maar de trigger kaart loopt niet sync ofzo ?
Geen idee of dat kan … ik probeer mee te denken 🤣

Met vriendelijke groet

Dennis Heijblom

Op 25 sep 2024 om 15:32 heeft magtimmermans ***@***.***> het volgende geschreven:

﻿

Ik snap het even niet. De error zegt dat de verbinding niet tot stand kan worden gebracht. (Internet issue of iets anders). Het gaat 2 keer goed en daarna niet meer. (Error at BuienAlarmGrabber.getForecasts (/app/BuienAlarmGrabber.js:23:22) at process.processTicksAndRejections).
Als ik hier jouw coordinaten invoer en heb het nu een dag laten draaien krijg ik netjes een notificatie 10 min voor dat de regen valt. In de logfiles van mijnzelf zie ik ook geen fout melding. En in alle die de logfiles die jij hebt gestuurd heb ik elke derde poging een foutmelding. Of dat toeval is weet ik niet.

**Comment by wdool** [comment]
Ik heb oude gegevens 71a33693-bd14-4805-b4f6-5c758fdf5490 Het is nu 10:18, dus loopt zo'n 10 uur achter, reboot van de app werkt niet.

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/a7c35523-091b-48f1-8d8a-2a66ad19a710" />

**Comment by magtimmermans** [comment]
De buien alarm data is 0. Ik heb even you link getest maar hij geeft geen regen aan 🙄. Lijkt er op dat de api niet meer bijgewerkt wordt. Geen idee of dit tijdelijk is of ze een nieuwe hebben. Ik zal er eens induiken
